site_name: Onboarding - Offboarding - Intune - Assets - Reporting
site_url: https://github.com/xxxmtixxx
theme:
  name: material
  icon:
    logo: fontawesome/solid/clipboard-list
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
    primary: indigo
    accent: deep orange 
  - scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode    
    primary: indigo
    accent: deep orange

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/xxxmtixxx
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@uh.whycanti
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/paulclemons/

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/xxxmtixxx"  target="_blank" rel="noopener">xxxMTIxxx</a>